In [1]:
races_df = spark.read.format('csv').options(header='true', inferSchema='true').load('/FileStore/tables/allegation_races.csv')
races_df.createOrReplaceTempView("allegation_races")

In [2]:
display(races_df.limit(5))

allegation_id,beat_id,if_officer_hispanic,if_officer_white,if_officer_black,if_officer_asianpac,if_officer_native,if_victim_white,if_victim_black,if_victim_hispanic,if_victim_asianpac,if_victim_native
72438,1,N,Y,N,N,N,Y,N,N,N,N
65519,1,Y,N,N,N,N,N,N,N,N,N
94393,1,N,Y,N,N,N,N,N,Y,N,N
64811,1,N,Y,N,Y,N,N,Y,N,N,N
60304,1,Y,Y,N,N,N,Y,N,N,N,N

In [3]:
%sql
SELECT
  CASE
    WHEN if_officer_white='Y' AND if_victim_white='Y' THEN 'white_white'
    WHEN if_officer_white='Y' AND if_victim_black='Y' THEN 'white_black'
    WHEN if_officer_white='Y' AND if_victim_hispanic='Y' THEN 'white_hispanic'
    WHEN if_officer_white='Y' AND if_victim_asianpac='Y' THEN 'white_asianpac'
    WHEN if_officer_white='Y' AND if_victim_native='Y' THEN 'white_native'
    WHEN if_officer_black='Y' AND if_victim_white='Y' THEN 'black_white'
    WHEN if_officer_black='Y' AND if_victim_black='Y' THEN 'black_black'
    WHEN if_officer_black='Y' AND if_victim_hispanic='Y' THEN 'black_hispanic'
    WHEN if_officer_black='Y' AND if_victim_asianpac='Y' THEN 'black_asianpac'
    WHEN if_officer_black='Y' AND if_victim_native='Y' THEN 'black_native'
    WHEN if_officer_hispanic='Y' AND if_victim_white='Y' THEN 'hispanic_white'
    WHEN if_officer_hispanic='Y' AND if_victim_black='Y' THEN 'hispanic_black'
    WHEN if_officer_hispanic='Y' AND if_victim_hispanic='Y' THEN 'hispanic_hispanic'
    WHEN if_officer_hispanic='Y' AND if_victim_asianpac='Y' THEN 'hispanic_asianpac'
    WHEN if_officer_hispanic='Y' AND if_victim_native='Y' THEN 'hispanic_native'
    WHEN if_officer_asianpac='Y' AND if_victim_white='Y' THEN 'asianpac_white'
    WHEN if_officer_asianpac='Y' AND if_victim_black='Y' THEN 'asianpac_black'
    WHEN if_officer_asianpac='Y' AND if_victim_hispanic='Y' THEN 'asianpac_hispanic'
    WHEN if_officer_asianpac='Y' AND if_victim_asianpac='Y' THEN 'asianpac_asianpac'
    WHEN if_officer_asianpac='Y' AND if_victim_native='Y' THEN 'asianpac_native'
    WHEN if_officer_native='Y' AND if_victim_white='Y' THEN 'native_white'
    WHEN if_officer_native='Y' AND if_victim_black='Y' THEN 'native_black'
    WHEN if_officer_native='Y' AND if_victim_hispanic='Y' THEN 'native_hispanic'
    WHEN if_officer_native='Y' AND if_victim_asianpac='Y' THEN 'native_asianpac'
    WHEN if_officer_native='Y' AND if_victim_native='Y' THEN 'native_native'
    END as race_to_race,
    COUNT(*)
FROM allegation_races
WHERE beat_id = 272
GROUP BY race_to_race
ORDER BY race_to_race DESC

race_to_race,count(1)
white_black,23
hispanic_black,3
black_white,2
black_black,37
null,2

In [4]:
%sql
SELECT
  CASE
    WHEN if_officer_white='Y' AND if_victim_white='Y' THEN 'white_white'
    WHEN if_officer_white='Y' AND if_victim_black='Y' THEN 'white_black'
    WHEN if_officer_white='Y' AND if_victim_hispanic='Y' THEN 'white_hispanic'
    WHEN if_officer_white='Y' AND if_victim_asianpac='Y' THEN 'white_asianpac'
    WHEN if_officer_white='Y' AND if_victim_native='Y' THEN 'white_native'
    WHEN if_officer_black='Y' AND if_victim_white='Y' THEN 'black_white'
    WHEN if_officer_black='Y' AND if_victim_black='Y' THEN 'black_black'
    WHEN if_officer_black='Y' AND if_victim_hispanic='Y' THEN 'black_hispanic'
    WHEN if_officer_black='Y' AND if_victim_asianpac='Y' THEN 'black_asianpac'
    WHEN if_officer_black='Y' AND if_victim_native='Y' THEN 'black_native'
    WHEN if_officer_hispanic='Y' AND if_victim_white='Y' THEN 'hispanic_white'
    WHEN if_officer_hispanic='Y' AND if_victim_black='Y' THEN 'hispanic_black'
    WHEN if_officer_hispanic='Y' AND if_victim_hispanic='Y' THEN 'hispanic_hispanic'
    WHEN if_officer_hispanic='Y' AND if_victim_asianpac='Y' THEN 'hispanic_asianpac'
    WHEN if_officer_hispanic='Y' AND if_victim_native='Y' THEN 'hispanic_native'
    WHEN if_officer_asianpac='Y' AND if_victim_white='Y' THEN 'asianpac_white'
    WHEN if_officer_asianpac='Y' AND if_victim_black='Y' THEN 'asianpac_black'
    WHEN if_officer_asianpac='Y' AND if_victim_hispanic='Y' THEN 'asianpac_hispanic'
    WHEN if_officer_asianpac='Y' AND if_victim_asianpac='Y' THEN 'asianpac_asianpac'
    WHEN if_officer_asianpac='Y' AND if_victim_native='Y' THEN 'asianpac_native'
    WHEN if_officer_native='Y' AND if_victim_white='Y' THEN 'native_white'
    WHEN if_officer_native='Y' AND if_victim_black='Y' THEN 'native_black'
    WHEN if_officer_native='Y' AND if_victim_hispanic='Y' THEN 'native_hispanic'
    WHEN if_officer_native='Y' AND if_victim_asianpac='Y' THEN 'native_asianpac'
    WHEN if_officer_native='Y' AND if_victim_native='Y' THEN 'native_native'
    END as race_to_race,
    COUNT(*)
FROM allegation_races
WHERE beat_id = 275
GROUP BY race_to_race
ORDER BY race_to_race DESC

race_to_race,count(1)
white_black,20
hispanic_black,5
black_black,23
null,2